language: python
python:
- '3.6'
env:
  global:
  - secure: JpiKIqwq8TrYJ6qDWp0GDkxBsBnCJJEVTJGxSqAfcpHF81CJFDTskBqSbo+ZsaEEviychOQbzNUAQuNns2dH14SQC4eOiuzrMpT8c9WRLm16koZZHAiq9qxD09ht9KJEBhhZ+vs1tij/Amh9lbxPs+7xYunk+vID1esskLNQU7QwOFSt0XEukln1RpEEHarc2KrO23bKrJKO/Ktv7pVCac+m/TPbUuxPrIkFIFwlrG8PTEwn0qLuC2jT3SxVE+oDrVPm6Rd666LfSuptnvQOlTB3h/kjjhwAlxDA0bsvlrNQL70XzltHZqMq907RfTGTIAXBtJ51VcELJ1z/8oh3hRidFRh6olZUzvxzODLFB4UfobIFmxJqRgV8VECq+WQx4Q0eYxzqn+Krc6MDvqt5tqhngkJ4+z7fUjU3Wy9/W4rfF6ChtjezmbGPy7SdMDcFd/yIChchIGkT7zZrm/0A+ejTg4zAGmmTwhrnuMRM7Kn8/HiRkC8EpKHVYxPqKUvQF5Ryve5kFEqiaJAdq3t9RpE+5Ire2WzbUrUk47elRwwDB1yDe9hSZAjp+q4vvGKYYb9Vp54dMQtaDa68aZbN2KtEfLLTnB3LKiE403tDWLbc++VsdVBtGbTx/WI9bi+Xzmjn+16iTRketOl+2RdxPQosXZIgb3onyAGgAgl1tqo=
  - secure: gA1/RzFW4qZP5O85/Ecsi2HWyfB3CTqMec5q5PQbQQwzqEYwJv8F61ZNKKEQaszBTv3dNfLkjVSbcdMwZ77enOll1eJlFbnVMpzcDM5N/xqju5uKVzMKkYX6uDJUJKPrdr3mpXe3NZNstLZOWqfjeKKrLuefNV3lnAB6DFECGgKos+4E0OaVCd10E3b4n8AnVqu2UAuls+ZGFcFLfJbBJeTP7EEBWFYqPH3J5Om3hS9nKjowf8sDoSFRyjfQFzX5/IOkmSR6FWqYeSIvoUywS75w8Y0Y7cIhvTYk9a57AIKoNVHE71vUsYUymZauKwM46e5ITT5IVlla98E/Hr3o2bq1eFTfozdWZ3nPHtmUY8xG57wFo8ToOEOxbFnKHQ6ZlhAQl6fF4+AZ+6QL1KVEHW+h/E02eOu3UIEiQda+KlM9fB213zXQb2SqLeg1ZwwOnUGua3McoZkAM3tEs/Z/DJMMp8sbiHZrA5GIvgCcykTgCrX5IRdo97q0cAfj9/Za9p82W0jiiZzoo5cKcUjifd3jvQAWMniFoOG/9/NGwJfsR2f1nZrVY2njsVfDlLeaCIp2F/k6EHj4n3UZy77886DkSCHi0oe+7lyXtwnPDnl2tazIEmLwYsuT8Z+Pglei8VZAmQUU917c55o/U89D3ZNlLI9xDPqtJkghl/qf69k=
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_93d72dfb0e2b_key -iv $encrypted_93d72dfb0e2b_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- pip install -r requirements.txt
script:
- pytest
after_success:
- pip freeze
- pip install -r requirements.txt
- pip freeze
- test $TRAVIS_BRANCH = "main" && zappa update
